{% set name = "psipred" %}
{% set version = "4.02" %}
# sha256 is the prefered checksum -- you can get it for a file with:
#  `openssl sha256 <file name>`.
# You may need the openssl package, available on conda-forge
#  `conda install openssl -c conda-forge``

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  url: http://bioinfadmin.cs.ucl.ac.uk/downloads/psipred/psipred.{{ version }}.tar.gz
  sha256: b4009b6a5f8b76c6d60ac91c4a743512d844864cf015c492fb6d1dc0d092c467
  patches:
  - makefile.patch

build:
  number: {{ environ.get("BUILD_NUMBER", 0) }}
  script: |
    make -C src
    make -C src DESTDIR="$PREFIX" install

requirements:
  build:
    - {{ compiler('c') }}

about:
  home: http://bioinf.cs.ucl.ac.uk/psipred/
  license: proprietary
  license_file: LICENSE
